<?php

namespace Database\Seeders;

use App\Models\Account\AccountOpeningBalance;
use Illuminate\Database\Seeder;

class OpeningBalanceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        AccountOpeningBalance::insert([
            [
                'inserted_by' => 1,
                'account_id' => 111,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 112,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 113,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 114,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 201,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 202,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 203,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 204,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 211,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 221,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 231,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 241,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 271,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 301,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 431,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 443,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 449,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 500,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 501,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 601,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 704,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 705,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 804,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 805,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 806,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 807,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 808,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 809,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 810,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
            [
                'inserted_by' => 1,
                'account_id' => 811,
                'account_sub_id' => 0,
                'amount' => 0.00,
                'location_id' => 1,
                'year' => date('Y'),
            ],
        ]);
    }
}
